// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'AssemblyProcesses': string;
  'AssemblyProcesses__aside': string;
  'AssemblyProcesses__header': string;
  'AssemblyProcesses__label': string;
  'AssemblyProcesses__title': string;
}
declare var cssExports: CssExports;
export = cssExports;
