export enum AssemblyActionTypes {
  SAGA_GET_ASSEMBLY = 'saga/GET_ASSEMBLY',

  SET_ASSEMBLY = 'SET_ASSEMBLY',
  SET_ASSEMBLY_LOADING_STATUS = 'SET_ASSEMBLY_LOADING_STATUS',
  REMOVE_ASSEMBLY_ITEM = 'REMOVE_ASSEMBLY_ITEM',
  RESET_ASSEMBLY_DATA = 'RESET_ASSEMBLY_DATA',
}
