// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Input': string;
  'Input__field': string;
  'Input_search': string;
}
declare var cssExports: CssExports;
export = cssExports;
