version: '3.7'

services:
  app:
    image: node:12-alpine
    working_dir: /app
    volumes:
      - ./app:/app
      - ./app/node_modules:/app/node_modules
      - ./app/dist:/app/dist
    ports:
      - 3000:3000
    command: sh -c "npm i && npm run build && npm run server"
    restart: always
