// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'StatusFilter': string;
  'StatusFilter__control': string;
  'StatusFilter__control_active': string;
  'StatusFilter__title': string;
}
declare var cssExports: CssExports;
export = cssExports;
