// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Switch': string;
  'Switch__control': string;
  'Switch__control_active': string;
}
declare var cssExports: CssExports;
export = cssExports;
