// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Sorting': string;
  'Sorting__label': string;
}
declare var cssExports: CssExports;
export = cssExports;
