// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'AssemblyCard': string;
  'AssemblyCard__button': string;
  'AssemblyCard__control': string;
  'AssemblyCard__controls': string;
  'AssemblyCard__img': string;
  'AssemblyCard__info': string;
  'AssemblyCard__label': string;
  'AssemblyCard__row': string;
  'AssemblyCard__status': string;
  'AssemblyCard__status_in_review': string;
  'AssemblyCard__title': string;
  'AssemblyCard__value': string;
  'AssemblyCard__value_green': string;
  'AssemblyCard__value_red': string;
}
declare var cssExports: CssExports;
export = cssExports;
