// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Filter': string;
  'Filter__title': string;
}
declare var cssExports: CssExports;
export = cssExports;
